<?php BigBoat::getHeader(); ?>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <a href="./menu/new" style="float: right;" class='btn btn-success'><i class="fas fa-plus-circle"></i> Novo</a>
        </div>
    </div>
    <br>
    <!-- get menu -->
    <div class="jumbotron">
        <div class="row">
            <div class="col-sm-6 col-md-4">
                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" src="https://http2.mlstatic.com/50-embalagem-big-boat-sushi-sashimi-hot-roll-delivery21x40-D_NQ_NP_170221-MLB20723156948_052016-F.jpg" alt="Image Cap">
                    <div class="card-body">
                        <h5 class="card-title">BigBoat 90</h5>
                        <p class="card-text" style="text-align:left; font-size: 80%">
                            10 Filad&eacute;lfia Salm&atilde;o <br>
                            10 Filad&eacute;lfia KaniKama <br>
                            10 Filad&eacute;lfia Camar&atilde;o <br>
                            10 Filad&eacute;lfia Skin <small>(Pele de salm&atilde;o grelhada)</small> <br>
                            10 Hossomaki Salm&atilde;o <br>
                            10 Hossomaki Kanikama <br>
                            10 Hossomaki Mix <small>(Salm&atilde;o e KaniKama)</small> <br>
                            04 Niguiri Salm&atilde;o <small>(Tradicional)</small> <br>
                            02 Niguiri Salm&atilde;o Selado <small>(Feito com ma&ccedil;arico)</small> <br>
                            10 Hot Filad&eacute;lfia com Alho Por&oacute; <br>
                            04 Hot Doce <small>(Banana com doce de leite)</small>
                            <br><br><span class="label label-success">R$ 69,90</span>
                            <br><br>Máximo de troca: 10 unidades.
                            <br>Acompanha Wassabi, Hashi, Shoyu.
                            <br>Kit para duas pessoas
                        </p>
                        <a href="#" class="fullwidth btn btn-primary">Editar</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php BigBoat::getFooter(); ?>