<?php BigBoat::getHeader(); ?>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
        <a href="/menu" class='btn btn-light'><i class="fas fa-arrow-left"></i> Voltar</a>
        <center><h4>Novo Cadastro</h4></center>
        </div>
    </div>
</div>
<?php BigBoat::getFooter(); ?>


Título
Composto (se composto tem relação n - n de pratos singulares)
Descrição (só aparece para itens não compostos)
Valor
Observações
Imagem