<?php BigBoat::getHeader(); ?>
<div class="container-fluid"><!--   Big container   -->
    <div class="row">
        <div class="col-sm-12">
            <div class="wizard-container"> <!--Wizard container-->
                <!--You can switch " data-color="purple" "  with one of the next bright colors: "green", "orange", "red", "blue" -->
                <div class="card wizard-card" data-color="green" id="wizardProfile">
                    <form action="" method="">
                        <div class="wizard-header">
                            <h3 class="wizard-title">Novo pedido</h3>
                        </div>
                        <div class="wizard-navigation">
                            <ul>
                                <li><a href="#pedido" data-toggle="tab">Pedido</a></li>
                                <li><a href="#identificacao" data-toggle="tab">Identificação</a></li>
                                <li><a href="#pagamento" data-toggle="tab">Pagamento</a></li>
                            </ul>
                        </div>

                        <div class="tab-content">
                            <div class="tab-pane" id="pedido" style="height: 45vh;overflow-y: auto">
                                <center id="loading-menu"><i style="margin-top:85px;" class="fas fa-spinner fa-spin"></i><br><span>Carregando pratos</span></center>
                                <div id="menu-list" class="row" style="width: 98% !important;"></div>
                            </div>
                            <div class="tab-pane" id="identificacao" style="height: 45vh;overflow-y: auto;">

                            </div>
                            <div class="tab-pane" id="pagamento" style="height: 45vh;overflow-y: auto">

                            </div>
                        </div>
                        <div class="wizard-footer">
                            <div class="pull-right">
                                <input type='button' class='btn btn-next btn-fill btn-success btn-wd' name='next' value='Próximo' />
                                <input type='button' class='btn btn-finish btn-fill btn-success btn-wd' name='finish' value='Finalizar Pedido' />
                            </div>
                            <div class="pull-left">
                                <input type='button' class='btn btn-previous btn-fill btn-default btn-wd' name='previous' value='Anterior' />
                            </div>
                            <div class="clearfix"></div>
                        </div>
                    </form>
                </div>
            </div> <!-- wizard container -->
        </div>
    </div><!-- end row -->
    
    <!-- modal -->
<!-- Modal -->
    <div class="modal fade" id="modalItemPedido" tabindex="-1" role="dialog" aria-labelledby="modalItemPedidoLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalItemPedidoLabel">Detalhes do Item</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="row" id="itemPedido"></div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <button type="button" class="btn btn-info">Adicionar</button>
                </div>
            </div>
        </div>
    </div>
    <!-- end modal -->
</div> <!--  big container -->
<?php BigBoat::getFooter('pedidos-new'); ?>