<?php BigBoat::getHeader(); ?>
<div class="container-fluid"><!--   Big container   -->
    <div class="row">
        <div class="col-sm-12">
            <div class="wizard-container"> <!--Wizard container-->
                <!--You can switch " data-color="purple" "  with one of the next bright colors: "green", "orange", "red", "blue" -->
                <div class="card wizard-card" data-color="green" id="wizardProfile">
                    <form action="" method="">
                        <div class="wizard-header">
                            <h3 class="wizard-title">Novo pedido</h3>
                        </div>
                        <div class="wizard-navigation">
                            <ul>
                                <li><a href="#pedido" data-toggle="tab">Pedido</a></li>
                                <li><a href="#identificacao" data-toggle="tab">Identificação</a></li>
                                <li><a href="#pagamento" data-toggle="tab">Pagamento</a></li>
                            </ul>
                        </div>

                        <div class="tab-content">
                            <div class="tab-pane" id="pedido" style="height: 45vh;overflow-y: auto">
                                <center id="loading-menu"><i style="margin-top:85px;" class="fas fa-spinner fa-spin"></i><br><span>Carregando pratos</span></center>
                                <div id="menu-list" class="row" style="width: 98% !important;"></div>
                            </div>
                            <div class="tab-pane" id="identificacao" style="height: 45vh;overflow-y: auto;">

                            </div>
                            <div class="tab-pane" id="pagamento" style="height: 45vh;overflow-y: auto">

                            </div>
                        </div>
                        <div class="wizard-footer">
                            <div class="pull-right">
                                <input type='button' class='btn btn-next btn-fill btn-success btn-wd' name='next' value='Próximo' />
                                <input type='button' class='btn btn-finish btn-fill btn-success btn-wd' name='finish' value='Finalizar Pedido' />
                            </div>
                            <div class="pull-left">
                                <input type='button' class='btn btn-previous btn-fill btn-default btn-wd' name='previous' value='Anterior' />
                            </div>
                            <div class="clearfix"></div>
                        </div>
                    </form>
                </div>
            </div> <!-- wizard container -->
        </div>
    </div><!-- end row -->
    
    <!-- modal -->
<!-- Modal -->
    <div class="modal fade" id="modalItemPedido" tabindex="-1" role="dialog" aria-labelledby="modalItemPedidoLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-body">
                        <center><i id="loading-menuItem" style="margin-top:85px; margin-bottom: 85px;" class="fas fa-spinner fa-spin"></i></center>
                    <div id="itemPedido"></div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <button type="button" class="btn btn-info" id="adicionarPedido">Adicionar</button>
                </div>
            </div>
        </div>
    </div>
    <!-- end modal -->
    <div class="collapse" id="collapseExample" style="position: absolute; z-index: 9999; top: 20%; left: 2.5%; width: 95%; padding: 7px; background-color: lightgray; border-radius: 3px;">
        <div class="card card-body" style="height: 500px;overflow-y: scroll;">
                <center><h3><i class="fab fa-opencart"></i>Carrinho</h3></center>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th scope="col" style="text-align: center; width: 15%">Quantidade</th>
                            <th scope="col" style="text-align: left;">Item</th>
                            <th scope="col" style="text-align: center; width: 10%">Valor</th>
                            <th scope="col" style="text-align: center; width: 5%">Remover</th>
                        </tr>
                    </thead>
                    <tbody id="tableItens">
                    </tbody>
                </table>
        </div>
    </div>
</div> <!--  big container -->
<footer>
    <nav class="navbar fixed-bottom navbar-light bg-light">
        <button class="btn btn-default" style="left: 44%" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
            <i class="fab fa-opencart"></i> Carrinho <span class="badge badge-light" id="quantidadeCarrinho">0</span>
        </button>
        <h5 style="right: 0">Total R$ <span id="valorCarrinho">0.00</span></h5>
    </nav>
</footer>
<?php BigBoat::getFooter('pedidos-new'); ?>